"""Default agent execution constants and configuration values for Johnston."""

# LLM & Compaction Defaults
DEFAULT_CONTEXT_LIMIT = 128000
CONTEXT_COMPACTION_THRESHOLD_RATIO = 0.75
COMPACTION_SUMMARIZE_RATIO = 0.90
DEFAULT_COMPACTION_USER_BUDGET = 20_000
DEFAULT_STREAM_TIMEOUT = 60.0
DEFAULT_CHUNK_TIMEOUT = 30.0
DEFAULT_MAX_TOKENS = 8192
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0
DEFAULT_RETRY_BACKOFF = 2.0
DEFAULT_MAX_RETRY_DELAY = 10.0
DEFAULT_CB_FAILURE_THRESHOLD = 3
DEFAULT_CB_COOLDOWN_SECONDS = 30.0
DEFAULT_AUTO_TITLE = True
DEFAULT_AUTO_TITLE_TIMEOUT = 8.0
DEFAULT_AUTO_TITLE_MAX_TOKENS = 30

# Tools Defaults
DEFAULT_SHELL_TIMEOUT = 120.0
DEFAULT_SHELL_MAX_CAP = 600.0
DEFAULT_SHELL_OUTPUT_CHARS = 4000
DEFAULT_TOOL_OUTPUT_CHARS = 8000
DEFAULT_TOOL_PAYLOAD_BYTES = 10 * 1024 * 1024  # 10 MB
DEFAULT_SNAPSHOT_LOG_BYTES = 50 * 1024 * 1024  # 50 MB
DEFAULT_MCP_CALL_TIMEOUT = 120.0
DEFAULT_MCP_INIT_TIMEOUT = 5.0
DEFAULT_WEB_FETCH_TIMEOUT = 20.0

# Subagents Defaults
MAX_CONCURRENT_SUBAGENTS = 5
DEFAULT_SUBAGENT_RESULT_MAX_CHARS = 15000
DEFAULT_SUBAGENT_WORKTREE_TIMEOUT = 15.0

# UI & Widgets Defaults
DEFAULT_PROMPT_HISTORY = 500
DEFAULT_STREAM_FLUSH_INTERVAL = 0.05
DEFAULT_CHAT_PAGE_SIZE = 50

# Storage & Logging Defaults
DEFAULT_LOG_MAX_BYTES = 5 * 1024 * 1024  # 5 MB
DEFAULT_LOG_MAX_AGE_DAYS = 7
DEFAULT_DISK_CACHE_TTL = 2.0

# Theme Palette Constants (Monochrome Slate)
THEME_PRIMARY = "#ffffff"
THEME_SECONDARY = "#f4f4f5"
THEME_MUTED = "#71717a"
THEME_SUBTLE = "#e4e4e7"

# Status Dot Colors
COLOR_STATUS_RUNNING = "#e5c07b"
COLOR_STATUS_ERROR = "#e06c75"
COLOR_STATUS_SUCCESS = "#98c379"

# Diff Highlighting Colors (OKLab balanced luminosity)
COLOR_DIFF_ADD_FG = "#46c05a"
COLOR_DIFF_ADD_BG = "on #15281e"
COLOR_DIFF_REMOVE_FG = "#f25555"
COLOR_DIFF_REMOVE_BG = "on #241416"
COLOR_DIFF_GUTTER = "#6e7681"

# Permissions Defaults
DEFAULT_PERMISSIONS = {
    "mode": "review",
    "default": "allow",
    "tools": {},
    "patterns": {},
}

