"""Default agent execution constants and configuration values for Johnston."""

# LLM & Compaction Defaults
DEFAULT_CONTEXT_LIMIT = 128000
DEFAULT_COMPACTION_THRESHOLD_RATIO = 0.75
DEFAULT_COMPACTION_SUMMARIZE_RATIO = 0.90
DEFAULT_COMPACTION_USER_BUDGET = 20_000
DEFAULT_STREAM_TIMEOUT = 60.0
DEFAULT_CHUNK_TIMEOUT = 30.0
DEFAULT_MAX_TOKENS = 32768
ESCALATED_MAX_TOKENS = 65536
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0
DEFAULT_RETRY_BACKOFF = 2.0
DEFAULT_MAX_RETRY_DELAY = 10.0
DEFAULT_CB_FAILURE_THRESHOLD = 3
DEFAULT_CB_COOLDOWN_SECONDS = 30.0
DEFAULT_AUTO_TITLE = False
DEFAULT_AUTO_TITLE_TIMEOUT = 15.0
DEFAULT_AUTO_TITLE_MAX_TOKENS = 1024
DEFAULT_AUTO_TITLE_MAX_LEN = 100
DEFAULT_AUTO_TITLE_MODEL = None
DEFAULT_CATALOG_CACHE_TTL = 86400.0
DEFAULT_AGENT_MD_MAX_CHARS = 20000

# Tools Defaults
DEFAULT_SHELL_TIMEOUT = 120.0
DEFAULT_SHELL_MAX_CAP = 600.0
DEFAULT_SHELL_OUTPUT_CHARS = 4000
DEFAULT_TOOL_OUTPUT_CHARS = 8000
DEFAULT_TOOL_PAYLOAD_BYTES = 10 * 1024 * 1024  # 10 MB
DEFAULT_SNAPSHOT_LOG_BYTES = 50 * 1024 * 1024  # 50 MB
DEFAULT_MCP_CALL_TIMEOUT = 120.0
DEFAULT_MCP_INIT_TIMEOUT = 5.0
DEFAULT_WEB_FETCH_TIMEOUT = 20.0
DEFAULT_READ_LINE_WINDOW = 800
DEFAULT_MAX_DIR_ENTRIES = 60
DEFAULT_DOC_CONVERSION_TIMEOUT = 30.0
DEFAULT_IMAGE_MAX_DIMENSION = 1568
DEFAULT_IMAGE_DIMENSION_LOW = 512
DEFAULT_IMAGE_DIMENSION_HIGH = 2048
DEFAULT_WEB_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36 Johnston/0.1"
)

# Read tool caches
DEFAULT_MAX_DOC_CACHE = 50
DEFAULT_DOC_CACHE_TTL = 600.0
DEFAULT_LINE_COUNT_CACHE_MAX = 500
# PNG-vs-JPEG size threshold for image reads (bytes)
DEFAULT_IMAGE_PNG_KEEP_BYTES = 1 * 1024 * 1024

# Web-fetch DNS (SSRF guard) cache
DEFAULT_DNS_CACHE_TTL = 60.0
DEFAULT_DNS_CACHE_MAX = 512

# MCP negative-lookup cache
DEFAULT_MCP_MISS_TTL = 30.0
DEFAULT_MCP_MISS_MAX = 512

# Subagents Defaults
DEFAULT_MAX_CONCURRENT_SUBAGENTS = 5
DEFAULT_SUBAGENT_RESULT_MAX_CHARS = 15000
DEFAULT_SUBAGENT_WORKTREE_TIMEOUT = 15.0

# UI & Widgets Defaults
DEFAULT_PROMPT_HISTORY = 500
DEFAULT_STREAM_FLUSH_INTERVAL = 0.05
DEFAULT_CHAT_PAGE_SIZE = 50
DEFAULT_PASTE_LINE_THRESHOLD = 10
DEFAULT_CHAT_INPUT_MAX_LINES = 6
DEFAULT_AUTOCOMPLETE_MAX_FILES = 1000
DEFAULT_SHELL_STREAM_BUFFER_BYTES = 200 * 1024

# Storage & Logging Defaults
DEFAULT_LOG_MAX_BYTES = 5 * 1024 * 1024  # 5 MB
DEFAULT_LOG_MAX_AGE_DAYS = 7
DEFAULT_DISK_CACHE_TTL = 2.0

# Theme Palette Constants (Monochrome Slate)
THEME_PRIMARY = "#ffffff"
THEME_SECONDARY = "#a1a1aa"
THEME_MUTED = "#71717a"
THEME_SUBTLE = "#52525b"

# Status Dot Colors
COLOR_STATUS_RUNNING = "#d4a259"
COLOR_STATUS_ERROR = "#d15858"
COLOR_STATUS_SUCCESS = "#5ea876"

# Diff Highlighting Colors (OKLab balanced luminosity)
COLOR_DIFF_ADD_FG = "#46c05a"
COLOR_DIFF_ADD_BG = "on #15281e"
COLOR_DIFF_REMOVE_FG = "#f25555"
COLOR_DIFF_REMOVE_BG = "on #241416"
COLOR_DIFF_GUTTER = "#6e7681"

# Permissions Defaults
DEFAULT_PERMISSIONS = {
    "mode": "review",
    "default": "allow",
    "tools": {},
    "patterns": {},
}

