"""Built-in themes and color palettes for Johnston."""

from pygments.token import Token

from core.domain.entities.theme import Theme

# --- Zinc Dark (Default Shadcn / Monochrome) ---
ZINC_DARK = Theme(
    name="zinc",
    label="Zinc Dark (Default)",
    dark=True,
    primary="#ffffff",
    secondary="#f4f4f5",
    muted="#71717a",
    subtle="#e4e4e7",
    tcss_vars={
        "bg-app": "#09090b",
        "bg-surface": "#18181b",
        "bg-elevated": "#27272a",
        "bg-hover": "#3f3f46",
        "border-subtle": "#27272a",
        "border-strong": "#3f3f46",
        "fg-primary": "#ffffff",
        "fg-body": "#f4f4f5",
        "fg-secondary": "#e4e4e7",
        "fg-card": "#d4d4d8",
        "fg-muted": "#a1a1aa",
        "fg-dim": "#71717a",
        "fg-faint": "#52525b",
        "fg-inverted": "#09090b",
        "bg-inverted": "#ffffff",
        "toast-info": "#61afef",
        "toast-warn": "#e5c07b",
        "toast-error": "#e06c75",
    },
    markdown_styles={
        "markdown.paragraph": "#f4f4f5",
        "markdown.text": "#f4f4f5",
        "markdown.h1": "bold #ffffff",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #ffffff",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #ffffff",
        "markdown.h4": "bold #ffffff",
        "markdown.h5": "bold #ffffff",
        "markdown.h6": "bold #ffffff",
        "markdown.code": "#ffffff on #27272a",
        "markdown.code_block": "#f4f4f5 on #27272a",
        "markdown.block_quote": "#e4e4e7 on #18181b",
        "markdown.list": "#a1a1aa",
        "markdown.item": "#f4f4f5",
        "markdown.item.bullet": "bold #a1a1aa",
        "markdown.item.number": "bold #a1a1aa",
        "markdown.table.border": "#27272a",
        "markdown.table.header": "bold #ffffff",
        "markdown.hr": "#27272a",
        "markdown.link": "underline #60a5fa",
        "markdown.link_url": "underline #60a5fa",
        "markdown.em": "italic #f4f4f5",
        "markdown.strong": "bold #ffffff",
        "markdown.s": "strike #71717a",
    },
    syntax_tokens={
        Token.Keyword: "#c678dd",
        Token.Keyword.Namespace: "#c678dd",
        Token.Keyword.Type: "#e5c07b",
        Token.Keyword.Declaration: "#c678dd",
        Token.Name.Function: "#61afef",
        Token.Name.Class: "#e5c07b",
        Token.Name.Tag: "#e06c75",
        Token.Name.Attribute: "#d19a66",
        Token.Name.Property: "#e06c75",
        Token.Name.Variable: "#e06c75",
        Token.Name.Constant: "#d19a66",
        Token.Name.Builtin: "#e5c07b",
        Token.Name.Label: "#61afef",
        Token.Name.Entity: "#56b6c2",
        Token.Name.Decorator: "#61afef",
        Token.Name.Other: "#e06c75",
        Token.Name: "#e06c75",
        Token.String: "#98c379",
        Token.String.Doc: "#98c379",
        Token.Number: "#d19a66",
        Token.Number.Hex: "#d19a66",
        Token.Literal: "#d19a66",
        Token.Operator: "#56b6c2",
        Token.Punctuation: "#abb2bf",
        Token.Comment: "#7f848e italic",
    },
)

# --- Catppuccin Mocha ---
CATPPUCCIN_MOCHA = Theme(
    name="catppuccin-mocha",
    label="Catppuccin Mocha",
    dark=True,
    primary="#cdd6f4",
    secondary="#bac2de",
    muted="#6c7086",
    subtle="#a6adc8",
    tcss_vars={
        "bg-app": "#1e1e2e",
        "bg-surface": "#181825",
        "bg-elevated": "#313244",
        "bg-hover": "#45475a",
        "border-subtle": "#313244",
        "border-strong": "#45475a",
        "fg-primary": "#cdd6f4",
        "fg-body": "#cdd6f4",
        "fg-secondary": "#bac2de",
        "fg-card": "#bac2de",
        "fg-muted": "#a6adc8",
        "fg-dim": "#6c7086",
        "fg-faint": "#585b70",
        "fg-inverted": "#1e1e2e",
        "bg-inverted": "#cdd6f4",
        "toast-info": "#89b4fa",
        "toast-warn": "#f9e2af",
        "toast-error": "#f38ba8",
    },
    markdown_styles={
        "markdown.paragraph": "#cdd6f4",
        "markdown.text": "#cdd6f4",
        "markdown.h1": "bold #cdd6f4",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #cdd6f4",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #cdd6f4",
        "markdown.h4": "bold #cdd6f4",
        "markdown.h5": "bold #cdd6f4",
        "markdown.h6": "bold #cdd6f4",
        "markdown.code": "#cdd6f4 on #313244",
        "markdown.code_block": "#cdd6f4 on #313244",
        "markdown.block_quote": "#bac2de on #181825",
        "markdown.list": "#a6adc8",
        "markdown.item": "#cdd6f4",
        "markdown.item.bullet": "bold #89b4fa",
        "markdown.item.number": "bold #89b4fa",
        "markdown.table.border": "#313244",
        "markdown.table.header": "bold #cdd6f4",
        "markdown.hr": "#313244",
        "markdown.link": "underline #89b4fa",
        "markdown.link_url": "underline #89b4fa",
        "markdown.em": "italic #cdd6f4",
        "markdown.strong": "bold #cdd6f4",
        "markdown.s": "strike #6c7086",
    },
    syntax_tokens={
        Token.Keyword: "#cba6f7",
        Token.Keyword.Namespace: "#cba6f7",
        Token.Keyword.Type: "#f9e2af",
        Token.Keyword.Declaration: "#cba6f7",
        Token.Name.Function: "#89b4fa",
        Token.Name.Class: "#f9e2af",
        Token.Name.Tag: "#f38ba8",
        Token.Name.Attribute: "#fab387",
        Token.Name.Property: "#f38ba8",
        Token.Name.Variable: "#f5e0dc",
        Token.Name.Constant: "#fab387",
        Token.Name.Builtin: "#f9e2af",
        Token.Name.Label: "#89b4fa",
        Token.Name.Entity: "#94e2d5",
        Token.Name.Decorator: "#89b4fa",
        Token.Name.Other: "#f38ba8",
        Token.Name: "#cdd6f4",
        Token.String: "#a6e3a1",
        Token.String.Doc: "#a6e3a1",
        Token.Number: "#fab387",
        Token.Number.Hex: "#fab387",
        Token.Literal: "#fab387",
        Token.Operator: "#94e2d5",
        Token.Punctuation: "#bac2de",
        Token.Comment: "#6c7086 italic",
    },
)

# --- Dracula ---
DRACULA = Theme(
    name="dracula",
    label="Dracula",
    dark=True,
    primary="#f8f8f2",
    secondary="#f8f8f2",
    muted="#6272a4",
    subtle="#bd93f9",
    tcss_vars={
        "bg-app": "#282a36",
        "bg-surface": "#21222c",
        "bg-elevated": "#44475a",
        "bg-hover": "#6272a4",
        "border-subtle": "#44475a",
        "border-strong": "#6272a4",
        "fg-primary": "#f8f8f2",
        "fg-body": "#f8f8f2",
        "fg-secondary": "#f8f8f2",
        "fg-card": "#f8f8f2",
        "fg-muted": "#bd93f9",
        "fg-dim": "#6272a4",
        "fg-faint": "#44475a",
        "fg-inverted": "#282a36",
        "bg-inverted": "#f8f8f2",
        "toast-info": "#8be9fd",
        "toast-warn": "#f1fa8c",
        "toast-error": "#ff5555",
    },
    markdown_styles={
        "markdown.paragraph": "#f8f8f2",
        "markdown.text": "#f8f8f2",
        "markdown.h1": "bold #bd93f9",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #ff79c6",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #50fa7b",
        "markdown.h4": "bold #8be9fd",
        "markdown.h5": "bold #f1fa8c",
        "markdown.h6": "bold #ffb86c",
        "markdown.code": "#f8f8f2 on #44475a",
        "markdown.code_block": "#f8f8f2 on #44475a",
        "markdown.block_quote": "#f8f8f2 on #21222c",
        "markdown.list": "#bd93f9",
        "markdown.item": "#f8f8f2",
        "markdown.item.bullet": "bold #ff79c6",
        "markdown.item.number": "bold #ff79c6",
        "markdown.table.border": "#44475a",
        "markdown.table.header": "bold #f8f8f2",
        "markdown.hr": "#44475a",
        "markdown.link": "underline #8be9fd",
        "markdown.link_url": "underline #8be9fd",
        "markdown.em": "italic #f8f8f2",
        "markdown.strong": "bold #f8f8f2",
        "markdown.s": "strike #6272a4",
    },
    syntax_tokens={
        Token.Keyword: "#ff79c6",
        Token.Keyword.Namespace: "#ff79c6",
        Token.Keyword.Type: "#8be9fd",
        Token.Keyword.Declaration: "#ff79c6",
        Token.Name.Function: "#50fa7b",
        Token.Name.Class: "#8be9fd",
        Token.Name.Tag: "#ff79c6",
        Token.Name.Attribute: "#50fa7b",
        Token.Name.Property: "#ffb86c",
        Token.Name.Variable: "#f8f8f2",
        Token.Name.Constant: "#bd93f9",
        Token.Name.Builtin: "#8be9fd",
        Token.Name.Label: "#8be9fd",
        Token.Name.Entity: "#8be9fd",
        Token.Name.Decorator: "#50fa7b",
        Token.Name.Other: "#f8f8f2",
        Token.Name: "#f8f8f2",
        Token.String: "#f1fa8c",
        Token.String.Doc: "#f1fa8c",
        Token.Number: "#bd93f9",
        Token.Number.Hex: "#bd93f9",
        Token.Literal: "#bd93f9",
        Token.Operator: "#ff79c6",
        Token.Punctuation: "#f8f8f2",
        Token.Comment: "#6272a4 italic",
    },
)

# --- Tokyo Night ---
TOKYO_NIGHT = Theme(
    name="tokyo-night",
    label="Tokyo Night",
    dark=True,
    primary="#c0caf5",
    secondary="#a9b1d6",
    muted="#565f89",
    subtle="#9aa5ce",
    tcss_vars={
        "bg-app": "#1a1b26",
        "bg-surface": "#16161e",
        "bg-elevated": "#24283b",
        "bg-hover": "#414868",
        "border-subtle": "#24283b",
        "border-strong": "#414868",
        "fg-primary": "#c0caf5",
        "fg-body": "#c0caf5",
        "fg-secondary": "#a9b1d6",
        "fg-card": "#a9b1d6",
        "fg-muted": "#9aa5ce",
        "fg-dim": "#565f89",
        "fg-faint": "#414868",
        "fg-inverted": "#1a1b26",
        "bg-inverted": "#c0caf5",
        "toast-info": "#7aa2f7",
        "toast-warn": "#e0af68",
        "toast-error": "#f7768e",
    },
    markdown_styles={
        "markdown.paragraph": "#c0caf5",
        "markdown.text": "#c0caf5",
        "markdown.h1": "bold #7aa2f7",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #bb9af7",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #7dcfff",
        "markdown.h4": "bold #7aa2f7",
        "markdown.h5": "bold #e0af68",
        "markdown.h6": "bold #f7768e",
        "markdown.code": "#c0caf5 on #24283b",
        "markdown.code_block": "#c0caf5 on #24283b",
        "markdown.block_quote": "#a9b1d6 on #16161e",
        "markdown.list": "#9aa5ce",
        "markdown.item": "#c0caf5",
        "markdown.item.bullet": "bold #7aa2f7",
        "markdown.item.number": "bold #7aa2f7",
        "markdown.table.border": "#24283b",
        "markdown.table.header": "bold #c0caf5",
        "markdown.hr": "#24283b",
        "markdown.link": "underline #7aa2f7",
        "markdown.link_url": "underline #7aa2f7",
        "markdown.em": "italic #c0caf5",
        "markdown.strong": "bold #c0caf5",
        "markdown.s": "strike #565f89",
    },
    syntax_tokens={
        Token.Keyword: "#bb9af7",
        Token.Keyword.Namespace: "#bb9af7",
        Token.Keyword.Type: "#2ac3de",
        Token.Keyword.Declaration: "#bb9af7",
        Token.Name.Function: "#7aa2f7",
        Token.Name.Class: "#2ac3de",
        Token.Name.Tag: "#f7768e",
        Token.Name.Attribute: "#bb9af7",
        Token.Name.Property: "#73daca",
        Token.Name.Variable: "#c0caf5",
        Token.Name.Constant: "#ff9e64",
        Token.Name.Builtin: "#2ac3de",
        Token.Name.Label: "#7aa2f7",
        Token.Name.Entity: "#7dcfff",
        Token.Name.Decorator: "#7aa2f7",
        Token.Name.Other: "#f7768e",
        Token.Name: "#c0caf5",
        Token.String: "#9ece6a",
        Token.String.Doc: "#9ece6a",
        Token.Number: "#ff9e64",
        Token.Number.Hex: "#ff9e64",
        Token.Literal: "#ff9e64",
        Token.Operator: "#89ddff",
        Token.Punctuation: "#a9b1d6",
        Token.Comment: "#565f89 italic",
    },
)

# --- Nord ---
NORD = Theme(
    name="nord",
    label="Nord",
    dark=True,
    primary="#eceff4",
    secondary="#d8dee9",
    muted="#4c566a",
    subtle="#88c0d0",
    tcss_vars={
        "bg-app": "#2e3440",
        "bg-surface": "#242933",
        "bg-elevated": "#3b4252",
        "bg-hover": "#434c5e",
        "border-subtle": "#3b4252",
        "border-strong": "#4c566a",
        "fg-primary": "#eceff4",
        "fg-body": "#e5e9f0",
        "fg-secondary": "#d8dee9",
        "fg-card": "#d8dee9",
        "fg-muted": "#88c0d0",
        "fg-dim": "#4c566a",
        "fg-faint": "#3b4252",
        "fg-inverted": "#2e3440",
        "bg-inverted": "#eceff4",
        "toast-info": "#88c0d0",
        "toast-warn": "#ebcb8b",
        "toast-error": "#bf616a",
    },
    markdown_styles={
        "markdown.paragraph": "#e5e9f0",
        "markdown.text": "#e5e9f0",
        "markdown.h1": "bold #88c0d0",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #81a1c1",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #5e81ac",
        "markdown.h4": "bold #88c0d0",
        "markdown.h5": "bold #ebcb8b",
        "markdown.h6": "bold #bf616a",
        "markdown.code": "#eceff4 on #3b4252",
        "markdown.code_block": "#e5e9f0 on #3b4252",
        "markdown.block_quote": "#d8dee9 on #242933",
        "markdown.list": "#88c0d0",
        "markdown.item": "#e5e9f0",
        "markdown.item.bullet": "bold #88c0d0",
        "markdown.item.number": "bold #88c0d0",
        "markdown.table.border": "#3b4252",
        "markdown.table.header": "bold #eceff4",
        "markdown.hr": "#3b4252",
        "markdown.link": "underline #88c0d0",
        "markdown.link_url": "underline #88c0d0",
        "markdown.em": "italic #e5e9f0",
        "markdown.strong": "bold #eceff4",
        "markdown.s": "strike #4c566a",
    },
    syntax_tokens={
        Token.Keyword: "#81a1c1",
        Token.Keyword.Namespace: "#81a1c1",
        Token.Keyword.Type: "#8fbcbb",
        Token.Keyword.Declaration: "#81a1c1",
        Token.Name.Function: "#88c0d0",
        Token.Name.Class: "#8fbcbb",
        Token.Name.Tag: "#81a1c1",
        Token.Name.Attribute: "#8fbcbb",
        Token.Name.Property: "#d8dee9",
        Token.Name.Variable: "#d8dee9",
        Token.Name.Constant: "#d08770",
        Token.Name.Builtin: "#81a1c1",
        Token.Name.Label: "#88c0d0",
        Token.Name.Entity: "#88c0d0",
        Token.Name.Decorator: "#d08770",
        Token.Name.Other: "#d8dee9",
        Token.Name: "#d8dee9",
        Token.String: "#a3be8c",
        Token.String.Doc: "#a3be8c",
        Token.Number: "#b48ead",
        Token.Number.Hex: "#b48ead",
        Token.Literal: "#b48ead",
        Token.Operator: "#81a1c1",
        Token.Punctuation: "#eceff4",
        Token.Comment: "#4c566a italic",
    },
)

# --- Zinc Light ---
ZINC_LIGHT = Theme(
    name="zinc-light",
    label="Zinc Light",
    dark=False,
    primary="#09090b",
    secondary="#18181b",
    muted="#71717a",
    subtle="#52525b",
    tcss_vars={
        "bg-app": "#ffffff",
        "bg-surface": "#f4f4f5",
        "bg-elevated": "#e4e4e7",
        "bg-hover": "#d4d4d8",
        "border-subtle": "#e4e4e7",
        "border-strong": "#d4d4d8",
        "fg-primary": "#09090b",
        "fg-body": "#18181b",
        "fg-secondary": "#27272a",
        "fg-card": "#27272a",
        "fg-muted": "#52525b",
        "fg-dim": "#71717a",
        "fg-faint": "#a1a1aa",
        "fg-inverted": "#ffffff",
        "bg-inverted": "#09090b",
        "toast-info": "#2563eb",
        "toast-warn": "#d97706",
        "toast-error": "#dc2626",
    },
    markdown_styles={
        "markdown.paragraph": "#18181b",
        "markdown.text": "#18181b",
        "markdown.h1": "bold #09090b",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #09090b",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #09090b",
        "markdown.h4": "bold #09090b",
        "markdown.h5": "bold #09090b",
        "markdown.h6": "bold #09090b",
        "markdown.code": "#09090b on #e4e4e7",
        "markdown.code_block": "#18181b on #e4e4e7",
        "markdown.block_quote": "#27272a on #f4f4f5",
        "markdown.list": "#52525b",
        "markdown.item": "#18181b",
        "markdown.item.bullet": "bold #52525b",
        "markdown.item.number": "bold #52525b",
        "markdown.table.border": "#e4e4e7",
        "markdown.table.header": "bold #09090b",
        "markdown.hr": "#e4e4e7",
        "markdown.link": "underline #2563eb",
        "markdown.link_url": "underline #2563eb",
        "markdown.em": "italic #18181b",
        "markdown.strong": "bold #09090b",
        "markdown.s": "strike #71717a",
    },
    syntax_tokens={
        Token.Keyword: "#a855f7",
        Token.Keyword.Namespace: "#a855f7",
        Token.Keyword.Type: "#d97706",
        Token.Keyword.Declaration: "#a855f7",
        Token.Name.Function: "#2563eb",
        Token.Name.Class: "#d97706",
        Token.Name.Tag: "#dc2626",
        Token.Name.Attribute: "#ea580c",
        Token.Name.Property: "#dc2626",
        Token.Name.Variable: "#09090b",
        Token.Name.Constant: "#ea580c",
        Token.Name.Builtin: "#d97706",
        Token.Name.Label: "#2563eb",
        Token.Name.Entity: "#0891b2",
        Token.Name.Decorator: "#2563eb",
        Token.Name.Other: "#dc2626",
        Token.Name: "#09090b",
        Token.String: "#16a34a",
        Token.String.Doc: "#16a34a",
        Token.Number: "#ea580c",
        Token.Number.Hex: "#ea580c",
        Token.Literal: "#ea580c",
        Token.Operator: "#0891b2",
        Token.Punctuation: "#52525b",
        Token.Comment: "#71717a italic",
    },
)

BUILTIN_THEMES: list[Theme] = [
    ZINC_DARK,
    CATPPUCCIN_MOCHA,
    DRACULA,
    TOKYO_NIGHT,
    NORD,
    ZINC_LIGHT,
]
