"""Built-in themes and color palettes for Johnston."""

from pygments.token import Token

from core.domain.entities.theme import Theme

# --- Zinc Dark (Default Shadcn / Monochrome) ---
ZINC_DARK = Theme(
    name="zinc",
    label="Zinc Dark",
    dark=True,
    primary="#ffffff",
    secondary="#f4f4f5",
    muted="#71717a",
    subtle="#e4e4e7",
    tcss_vars={
        "bg-app": "#09090b",
        "bg-surface": "#18181b",
        "bg-elevated": "#27272a",
        "bg-hover": "#3f3f46",
        "border-subtle": "#27272a",
        "border-strong": "#3f3f46",
        "fg-primary": "#ffffff",
        "fg-body": "#f4f4f5",
        "fg-secondary": "#e4e4e7",
        "fg-card": "#d4d4d8",
        "fg-muted": "#a1a1aa",
        "fg-dim": "#71717a",
        "fg-faint": "#52525b",
        "fg-inverted": "#09090b",
        "bg-inverted": "#ffffff",
        "toast-info": "#61afef",
        "toast-warn": "#e5c07b",
        "toast-error": "#e06c75",
    },
    markdown_styles={
        "markdown.paragraph": "#f4f4f5",
        "markdown.text": "#f4f4f5",
        "markdown.h1": "bold #ffffff",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #ffffff",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #ffffff",
        "markdown.h4": "bold #ffffff",
        "markdown.h5": "bold #ffffff",
        "markdown.h6": "bold #ffffff",
        "markdown.code": "#ffffff on #27272a",
        "markdown.code_block": "#f4f4f5 on #27272a",
        "markdown.block_quote": "#e4e4e7 on #18181b",
        "markdown.list": "#a1a1aa",
        "markdown.item": "#f4f4f5",
        "markdown.item.bullet": "bold #a1a1aa",
        "markdown.item.number": "bold #a1a1aa",
        "markdown.table.border": "#27272a",
        "markdown.table.header": "bold #ffffff",
        "markdown.hr": "#27272a",
        "markdown.link": "underline #60a5fa",
        "markdown.link_url": "underline #60a5fa",
        "markdown.em": "italic #f4f4f5",
        "markdown.strong": "bold #ffffff",
        "markdown.s": "strike #71717a",
    },
    syntax_tokens={
        Token.Keyword: "#c678dd",
        Token.Keyword.Namespace: "#c678dd",
        Token.Keyword.Type: "#e5c07b",
        Token.Keyword.Declaration: "#c678dd",
        Token.Name.Function: "#61afef",
        Token.Name.Class: "#e5c07b",
        Token.Name.Tag: "#e06c75",
        Token.Name.Attribute: "#d19a66",
        Token.Name.Property: "#e06c75",
        Token.Name.Variable: "#e06c75",
        Token.Name.Constant: "#d19a66",
        Token.Name.Builtin: "#e5c07b",
        Token.Name.Label: "#61afef",
        Token.Name.Entity: "#56b6c2",
        Token.Name.Decorator: "#61afef",
        Token.Name.Other: "#e06c75",
        Token.Name: "#e06c75",
        Token.String: "#98c379",
        Token.String.Doc: "#98c379",
        Token.Number: "#d19a66",
        Token.Number.Hex: "#d19a66",
        Token.Literal: "#d19a66",
        Token.Operator: "#56b6c2",
        Token.Punctuation: "#abb2bf",
        Token.Comment: "#7f848e italic",
    },
)

# --- Catppuccin Mocha ---
CATPPUCCIN_MOCHA = Theme(
    name="catppuccin-mocha",
    label="Catppuccin Mocha",
    dark=True,
    primary="#cdd6f4",
    secondary="#bac2de",
    muted="#6c7086",
    subtle="#a6adc8",
    tcss_vars={
        "bg-app": "#1e1e2e",
        "bg-surface": "#181825",
        "bg-elevated": "#313244",
        "bg-hover": "#45475a",
        "border-subtle": "#313244",
        "border-strong": "#45475a",
        "fg-primary": "#cdd6f4",
        "fg-body": "#cdd6f4",
        "fg-secondary": "#bac2de",
        "fg-card": "#bac2de",
        "fg-muted": "#a6adc8",
        "fg-dim": "#6c7086",
        "fg-faint": "#585b70",
        "fg-inverted": "#1e1e2e",
        "bg-inverted": "#cdd6f4",
        "toast-info": "#89b4fa",
        "toast-warn": "#f9e2af",
        "toast-error": "#f38ba8",
    },
    markdown_styles={
        "markdown.paragraph": "#cdd6f4",
        "markdown.text": "#cdd6f4",
        "markdown.h1": "bold #cdd6f4",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #cdd6f4",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #cdd6f4",
        "markdown.h4": "bold #cdd6f4",
        "markdown.h5": "bold #cdd6f4",
        "markdown.h6": "bold #cdd6f4",
        "markdown.code": "#cdd6f4 on #313244",
        "markdown.code_block": "#cdd6f4 on #313244",
        "markdown.block_quote": "#bac2de on #181825",
        "markdown.list": "#a6adc8",
        "markdown.item": "#cdd6f4",
        "markdown.item.bullet": "bold #89b4fa",
        "markdown.item.number": "bold #89b4fa",
        "markdown.table.border": "#313244",
        "markdown.table.header": "bold #cdd6f4",
        "markdown.hr": "#313244",
        "markdown.link": "underline #89b4fa",
        "markdown.link_url": "underline #89b4fa",
        "markdown.em": "italic #cdd6f4",
        "markdown.strong": "bold #cdd6f4",
        "markdown.s": "strike #6c7086",
    },
    syntax_tokens={
        Token.Keyword: "#cba6f7",
        Token.Keyword.Namespace: "#cba6f7",
        Token.Keyword.Type: "#f9e2af",
        Token.Keyword.Declaration: "#cba6f7",
        Token.Name.Function: "#89b4fa",
        Token.Name.Class: "#f9e2af",
        Token.Name.Tag: "#f38ba8",
        Token.Name.Attribute: "#fab387",
        Token.Name.Property: "#f38ba8",
        Token.Name.Variable: "#f5e0dc",
        Token.Name.Constant: "#fab387",
        Token.Name.Builtin: "#f9e2af",
        Token.Name.Label: "#89b4fa",
        Token.Name.Entity: "#94e2d5",
        Token.Name.Decorator: "#89b4fa",
        Token.Name.Other: "#f38ba8",
        Token.Name: "#cdd6f4",
        Token.String: "#a6e3a1",
        Token.String.Doc: "#a6e3a1",
        Token.Number: "#fab387",
        Token.Number.Hex: "#fab387",
        Token.Literal: "#fab387",
        Token.Operator: "#94e2d5",
        Token.Punctuation: "#bac2de",
        Token.Comment: "#6c7086 italic",
    },
)

# --- Dracula ---
DRACULA = Theme(
    name="dracula",
    label="Dracula",
    dark=True,
    primary="#f8f8f2",
    secondary="#f8f8f2",
    muted="#6272a4",
    subtle="#bd93f9",
    tcss_vars={
        "bg-app": "#282a36",
        "bg-surface": "#21222c",
        "bg-elevated": "#44475a",
        "bg-hover": "#6272a4",
        "border-subtle": "#44475a",
        "border-strong": "#6272a4",
        "fg-primary": "#f8f8f2",
        "fg-body": "#f8f8f2",
        "fg-secondary": "#f8f8f2",
        "fg-card": "#f8f8f2",
        "fg-muted": "#bd93f9",
        "fg-dim": "#6272a4",
        "fg-faint": "#44475a",
        "fg-inverted": "#282a36",
        "bg-inverted": "#f8f8f2",
        "toast-info": "#8be9fd",
        "toast-warn": "#f1fa8c",
        "toast-error": "#ff5555",
    },
    markdown_styles={
        "markdown.paragraph": "#f8f8f2",
        "markdown.text": "#f8f8f2",
        "markdown.h1": "bold #bd93f9",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #ff79c6",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #50fa7b",
        "markdown.h4": "bold #8be9fd",
        "markdown.h5": "bold #f1fa8c",
        "markdown.h6": "bold #ffb86c",
        "markdown.code": "#f8f8f2 on #44475a",
        "markdown.code_block": "#f8f8f2 on #44475a",
        "markdown.block_quote": "#f8f8f2 on #21222c",
        "markdown.list": "#bd93f9",
        "markdown.item": "#f8f8f2",
        "markdown.item.bullet": "bold #ff79c6",
        "markdown.item.number": "bold #ff79c6",
        "markdown.table.border": "#44475a",
        "markdown.table.header": "bold #f8f8f2",
        "markdown.hr": "#44475a",
        "markdown.link": "underline #8be9fd",
        "markdown.link_url": "underline #8be9fd",
        "markdown.em": "italic #f8f8f2",
        "markdown.strong": "bold #f8f8f2",
        "markdown.s": "strike #6272a4",
    },
    syntax_tokens={
        Token.Keyword: "#ff79c6",
        Token.Keyword.Namespace: "#ff79c6",
        Token.Keyword.Type: "#8be9fd",
        Token.Keyword.Declaration: "#ff79c6",
        Token.Name.Function: "#50fa7b",
        Token.Name.Class: "#8be9fd",
        Token.Name.Tag: "#ff79c6",
        Token.Name.Attribute: "#50fa7b",
        Token.Name.Property: "#ffb86c",
        Token.Name.Variable: "#f8f8f2",
        Token.Name.Constant: "#bd93f9",
        Token.Name.Builtin: "#8be9fd",
        Token.Name.Label: "#8be9fd",
        Token.Name.Entity: "#8be9fd",
        Token.Name.Decorator: "#50fa7b",
        Token.Name.Other: "#f8f8f2",
        Token.Name: "#f8f8f2",
        Token.String: "#f1fa8c",
        Token.String.Doc: "#f1fa8c",
        Token.Number: "#bd93f9",
        Token.Number.Hex: "#bd93f9",
        Token.Literal: "#bd93f9",
        Token.Operator: "#ff79c6",
        Token.Punctuation: "#f8f8f2",
        Token.Comment: "#6272a4 italic",
    },
)

# --- Tokyo Night ---
TOKYO_NIGHT = Theme(
    name="tokyo-night",
    label="Tokyo Night",
    dark=True,
    primary="#c0caf5",
    secondary="#a9b1d6",
    muted="#565f89",
    subtle="#9aa5ce",
    tcss_vars={
        "bg-app": "#1a1b26",
        "bg-surface": "#16161e",
        "bg-elevated": "#24283b",
        "bg-hover": "#414868",
        "border-subtle": "#24283b",
        "border-strong": "#414868",
        "fg-primary": "#c0caf5",
        "fg-body": "#c0caf5",
        "fg-secondary": "#a9b1d6",
        "fg-card": "#a9b1d6",
        "fg-muted": "#9aa5ce",
        "fg-dim": "#565f89",
        "fg-faint": "#414868",
        "fg-inverted": "#1a1b26",
        "bg-inverted": "#c0caf5",
        "toast-info": "#7aa2f7",
        "toast-warn": "#e0af68",
        "toast-error": "#f7768e",
    },
    markdown_styles={
        "markdown.paragraph": "#c0caf5",
        "markdown.text": "#c0caf5",
        "markdown.h1": "bold #7aa2f7",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #bb9af7",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #7dcfff",
        "markdown.h4": "bold #7aa2f7",
        "markdown.h5": "bold #e0af68",
        "markdown.h6": "bold #f7768e",
        "markdown.code": "#c0caf5 on #24283b",
        "markdown.code_block": "#c0caf5 on #24283b",
        "markdown.block_quote": "#a9b1d6 on #16161e",
        "markdown.list": "#9aa5ce",
        "markdown.item": "#c0caf5",
        "markdown.item.bullet": "bold #7aa2f7",
        "markdown.item.number": "bold #7aa2f7",
        "markdown.table.border": "#24283b",
        "markdown.table.header": "bold #c0caf5",
        "markdown.hr": "#24283b",
        "markdown.link": "underline #7aa2f7",
        "markdown.link_url": "underline #7aa2f7",
        "markdown.em": "italic #c0caf5",
        "markdown.strong": "bold #c0caf5",
        "markdown.s": "strike #565f89",
    },
    syntax_tokens={
        Token.Keyword: "#bb9af7",
        Token.Keyword.Namespace: "#bb9af7",
        Token.Keyword.Type: "#2ac3de",
        Token.Keyword.Declaration: "#bb9af7",
        Token.Name.Function: "#7aa2f7",
        Token.Name.Class: "#2ac3de",
        Token.Name.Tag: "#f7768e",
        Token.Name.Attribute: "#bb9af7",
        Token.Name.Property: "#73daca",
        Token.Name.Variable: "#c0caf5",
        Token.Name.Constant: "#ff9e64",
        Token.Name.Builtin: "#2ac3de",
        Token.Name.Label: "#7aa2f7",
        Token.Name.Entity: "#7dcfff",
        Token.Name.Decorator: "#7aa2f7",
        Token.Name.Other: "#f7768e",
        Token.Name: "#c0caf5",
        Token.String: "#9ece6a",
        Token.String.Doc: "#9ece6a",
        Token.Number: "#ff9e64",
        Token.Number.Hex: "#ff9e64",
        Token.Literal: "#ff9e64",
        Token.Operator: "#89ddff",
        Token.Punctuation: "#a9b1d6",
        Token.Comment: "#565f89 italic",
    },
)

# --- Nord ---
NORD = Theme(
    name="nord",
    label="Nord",
    dark=True,
    primary="#eceff4",
    secondary="#d8dee9",
    muted="#4c566a",
    subtle="#88c0d0",
    tcss_vars={
        "bg-app": "#2e3440",
        "bg-surface": "#242933",
        "bg-elevated": "#3b4252",
        "bg-hover": "#434c5e",
        "border-subtle": "#3b4252",
        "border-strong": "#4c566a",
        "fg-primary": "#eceff4",
        "fg-body": "#e5e9f0",
        "fg-secondary": "#d8dee9",
        "fg-card": "#d8dee9",
        "fg-muted": "#88c0d0",
        "fg-dim": "#4c566a",
        "fg-faint": "#3b4252",
        "fg-inverted": "#2e3440",
        "bg-inverted": "#eceff4",
        "toast-info": "#88c0d0",
        "toast-warn": "#ebcb8b",
        "toast-error": "#bf616a",
    },
    markdown_styles={
        "markdown.paragraph": "#e5e9f0",
        "markdown.text": "#e5e9f0",
        "markdown.h1": "bold #88c0d0",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #81a1c1",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #5e81ac",
        "markdown.h4": "bold #88c0d0",
        "markdown.h5": "bold #ebcb8b",
        "markdown.h6": "bold #bf616a",
        "markdown.code": "#eceff4 on #3b4252",
        "markdown.code_block": "#e5e9f0 on #3b4252",
        "markdown.block_quote": "#d8dee9 on #242933",
        "markdown.list": "#88c0d0",
        "markdown.item": "#e5e9f0",
        "markdown.item.bullet": "bold #88c0d0",
        "markdown.item.number": "bold #88c0d0",
        "markdown.table.border": "#3b4252",
        "markdown.table.header": "bold #eceff4",
        "markdown.hr": "#3b4252",
        "markdown.link": "underline #88c0d0",
        "markdown.link_url": "underline #88c0d0",
        "markdown.em": "italic #e5e9f0",
        "markdown.strong": "bold #eceff4",
        "markdown.s": "strike #4c566a",
    },
    syntax_tokens={
        Token.Keyword: "#81a1c1",
        Token.Keyword.Namespace: "#81a1c1",
        Token.Keyword.Type: "#8fbcbb",
        Token.Keyword.Declaration: "#81a1c1",
        Token.Name.Function: "#88c0d0",
        Token.Name.Class: "#8fbcbb",
        Token.Name.Tag: "#81a1c1",
        Token.Name.Attribute: "#8fbcbb",
        Token.Name.Property: "#d8dee9",
        Token.Name.Variable: "#d8dee9",
        Token.Name.Constant: "#d08770",
        Token.Name.Builtin: "#81a1c1",
        Token.Name.Label: "#88c0d0",
        Token.Name.Entity: "#88c0d0",
        Token.Name.Decorator: "#d08770",
        Token.Name.Other: "#d8dee9",
        Token.Name: "#d8dee9",
        Token.String: "#a3be8c",
        Token.String.Doc: "#a3be8c",
        Token.Number: "#b48ead",
        Token.Number.Hex: "#b48ead",
        Token.Literal: "#b48ead",
        Token.Operator: "#81a1c1",
        Token.Punctuation: "#eceff4",
        Token.Comment: "#4c566a italic",
    },
)

# --- Gruvbox Dark ---
GRUVBOX = Theme(
    name="gruvbox",
    label="Gruvbox Dark",
    dark=True,
    primary="#ebdbb2",
    secondary="#d5c4a1",
    muted="#928374",
    subtle="#bdae93",
    tcss_vars={
        "bg-app": "#282828",
        "bg-surface": "#1d2021",
        "bg-elevated": "#3c3836",
        "bg-hover": "#504945",
        "border-subtle": "#3c3836",
        "border-strong": "#504945",
        "fg-primary": "#ebdbb2",
        "fg-body": "#ebdbb2",
        "fg-secondary": "#d5c4a1",
        "fg-card": "#d5c4a1",
        "fg-muted": "#bdae93",
        "fg-dim": "#928374",
        "fg-faint": "#665c54",
        "fg-inverted": "#282828",
        "bg-inverted": "#ebdbb2",
        "toast-info": "#83a598",
        "toast-warn": "#fabd2f",
        "toast-error": "#fb4934",
    },
    markdown_styles={
        "markdown.paragraph": "#ebdbb2",
        "markdown.text": "#ebdbb2",
        "markdown.h1": "bold #fabd2f",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #fe8019",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #b8bb26",
        "markdown.h4": "bold #83a598",
        "markdown.h5": "bold #d3869b",
        "markdown.h6": "bold #8ec07c",
        "markdown.code": "#ebdbb2 on #3c3836",
        "markdown.code_block": "#ebdbb2 on #3c3836",
        "markdown.block_quote": "#d5c4a1 on #1d2021",
        "markdown.list": "#bdae93",
        "markdown.item": "#ebdbb2",
        "markdown.item.bullet": "bold #fabd2f",
        "markdown.item.number": "bold #fabd2f",
        "markdown.table.border": "#3c3836",
        "markdown.table.header": "bold #ebdbb2",
        "markdown.hr": "#3c3836",
        "markdown.link": "underline #83a598",
        "markdown.link_url": "underline #83a598",
        "markdown.em": "italic #ebdbb2",
        "markdown.strong": "bold #ebdbb2",
        "markdown.s": "strike #928374",
    },
    syntax_tokens={
        Token.Keyword: "#fb4934",
        Token.Keyword.Namespace: "#fb4934",
        Token.Keyword.Type: "#fabd2f",
        Token.Keyword.Declaration: "#fb4934",
        Token.Name.Function: "#b8bb26",
        Token.Name.Class: "#fabd2f",
        Token.Name.Tag: "#fb4934",
        Token.Name.Attribute: "#b8bb26",
        Token.Name.Property: "#83a598",
        Token.Name.Variable: "#ebdbb2",
        Token.Name.Constant: "#d3869b",
        Token.Name.Builtin: "#fabd2f",
        Token.Name.Label: "#83a598",
        Token.Name.Entity: "#8ec07c",
        Token.Name.Decorator: "#fe8019",
        Token.Name.Other: "#ebdbb2",
        Token.Name: "#ebdbb2",
        Token.String: "#b8bb26",
        Token.String.Doc: "#b8bb26",
        Token.Number: "#d3869b",
        Token.Number.Hex: "#d3869b",
        Token.Literal: "#d3869b",
        Token.Operator: "#8ec07c",
        Token.Punctuation: "#ebdbb2",
        Token.Comment: "#928374 italic",
    },
)

# --- One Dark Pro ---
ONE_DARK = Theme(
    name="one-dark",
    label="One Dark Pro",
    dark=True,
    primary="#abb2bf",
    secondary="#dcdfe4",
    muted="#5c6370",
    subtle="#828997",
    tcss_vars={
        "bg-app": "#21252b",
        "bg-surface": "#1e2227",
        "bg-elevated": "#282c34",
        "bg-hover": "#3a3f4b",
        "border-subtle": "#282c34",
        "border-strong": "#3a3f4b",
        "fg-primary": "#abb2bf",
        "fg-body": "#abb2bf",
        "fg-secondary": "#dcdfe4",
        "fg-card": "#dcdfe4",
        "fg-muted": "#828997",
        "fg-dim": "#5c6370",
        "fg-faint": "#3e4451",
        "fg-inverted": "#21252b",
        "bg-inverted": "#abb2bf",
        "toast-info": "#61afef",
        "toast-warn": "#e5c07b",
        "toast-error": "#e06c75",
    },
    markdown_styles={
        "markdown.paragraph": "#abb2bf",
        "markdown.text": "#abb2bf",
        "markdown.h1": "bold #61afef",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #c678dd",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #98c379",
        "markdown.h4": "bold #61afef",
        "markdown.h5": "bold #e5c07b",
        "markdown.h6": "bold #e06c75",
        "markdown.code": "#abb2bf on #282c34",
        "markdown.code_block": "#abb2bf on #282c34",
        "markdown.block_quote": "#dcdfe4 on #1e2227",
        "markdown.list": "#828997",
        "markdown.item": "#abb2bf",
        "markdown.item.bullet": "bold #61afef",
        "markdown.item.number": "bold #61afef",
        "markdown.table.border": "#282c34",
        "markdown.table.header": "bold #abb2bf",
        "markdown.hr": "#282c34",
        "markdown.link": "underline #61afef",
        "markdown.link_url": "underline #61afef",
        "markdown.em": "italic #abb2bf",
        "markdown.strong": "bold #abb2bf",
        "markdown.s": "strike #5c6370",
    },
    syntax_tokens={
        Token.Keyword: "#c678dd",
        Token.Keyword.Namespace: "#c678dd",
        Token.Keyword.Type: "#e5c07b",
        Token.Keyword.Declaration: "#c678dd",
        Token.Name.Function: "#61afef",
        Token.Name.Class: "#e5c07b",
        Token.Name.Tag: "#e06c75",
        Token.Name.Attribute: "#d19a66",
        Token.Name.Property: "#e06c75",
        Token.Name.Variable: "#e06c75",
        Token.Name.Constant: "#d19a66",
        Token.Name.Builtin: "#e5c07b",
        Token.Name.Label: "#61afef",
        Token.Name.Entity: "#56b6c2",
        Token.Name.Decorator: "#61afef",
        Token.Name.Other: "#e06c75",
        Token.Name: "#e06c75",
        Token.String: "#98c379",
        Token.String.Doc: "#98c379",
        Token.Number: "#d19a66",
        Token.Number.Hex: "#d19a66",
        Token.Literal: "#d19a66",
        Token.Operator: "#56b6c2",
        Token.Punctuation: "#abb2bf",
        Token.Comment: "#5c6370 italic",
    },
)

# --- Rose Pine ---
ROSE_PINE = Theme(
    name="rose-pine",
    label="Rose Pine",
    dark=True,
    primary="#e0def4",
    secondary="#e0def4",
    muted="#6e6a86",
    subtle="#908caa",
    tcss_vars={
        "bg-app": "#191724",
        "bg-surface": "#1f1d2e",
        "bg-elevated": "#26233a",
        "bg-hover": "#403d52",
        "border-subtle": "#26233a",
        "border-strong": "#403d52",
        "fg-primary": "#e0def4",
        "fg-body": "#e0def4",
        "fg-secondary": "#e0def4",
        "fg-card": "#e0def4",
        "fg-muted": "#908caa",
        "fg-dim": "#6e6a86",
        "fg-faint": "#26233a",
        "fg-inverted": "#191724",
        "bg-inverted": "#e0def4",
        "toast-info": "#9ccfd8",
        "toast-warn": "#f6c177",
        "toast-error": "#eb6f92",
    },
    markdown_styles={
        "markdown.paragraph": "#e0def4",
        "markdown.text": "#e0def4",
        "markdown.h1": "bold #ebbcba",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #c4a7e7",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #9ccfd8",
        "markdown.h4": "bold #31748f",
        "markdown.h5": "bold #f6c177",
        "markdown.h6": "bold #eb6f92",
        "markdown.code": "#e0def4 on #26233a",
        "markdown.code_block": "#e0def4 on #26233a",
        "markdown.block_quote": "#e0def4 on #1f1d2e",
        "markdown.list": "#908caa",
        "markdown.item": "#e0def4",
        "markdown.item.bullet": "bold #ebbcba",
        "markdown.item.number": "bold #ebbcba",
        "markdown.table.border": "#26233a",
        "markdown.table.header": "bold #e0def4",
        "markdown.hr": "#26233a",
        "markdown.link": "underline #9ccfd8",
        "markdown.link_url": "underline #9ccfd8",
        "markdown.em": "italic #e0def4",
        "markdown.strong": "bold #e0def4",
        "markdown.s": "strike #6e6a86",
    },
    syntax_tokens={
        Token.Keyword: "#31748f",
        Token.Keyword.Namespace: "#31748f",
        Token.Keyword.Type: "#9ccfd8",
        Token.Keyword.Declaration: "#31748f",
        Token.Name.Function: "#ebbcba",
        Token.Name.Class: "#9ccfd8",
        Token.Name.Tag: "#eb6f92",
        Token.Name.Attribute: "#c4a7e7",
        Token.Name.Property: "#eb6f92",
        Token.Name.Variable: "#e0def4",
        Token.Name.Constant: "#ea9a97",
        Token.Name.Builtin: "#9ccfd8",
        Token.Name.Label: "#ebbcba",
        Token.Name.Entity: "#9ccfd8",
        Token.Name.Decorator: "#c4a7e7",
        Token.Name.Other: "#eb6f92",
        Token.Name: "#e0def4",
        Token.String: "#f6c177",
        Token.String.Doc: "#f6c177",
        Token.Number: "#eb6f92",
        Token.Number.Hex: "#eb6f92",
        Token.Literal: "#eb6f92",
        Token.Operator: "#c4a7e7",
        Token.Punctuation: "#e0def4",
        Token.Comment: "#6e6a86 italic",
    },
)

# --- Monokai Pro ---
MONOKAI_PRO = Theme(
    name="monokai-pro",
    label="Monokai Pro",
    dark=True,
    primary="#fcfcfa",
    secondary="#fcfcfa",
    muted="#727072",
    subtle="#939293",
    tcss_vars={
        "bg-app": "#2d2a2e",
        "bg-surface": "#221f22",
        "bg-elevated": "#3a3539",
        "bg-hover": "#4a444a",
        "border-subtle": "#3a3539",
        "border-strong": "#4a444a",
        "fg-primary": "#fcfcfa",
        "fg-body": "#fcfcfa",
        "fg-secondary": "#fcfcfa",
        "fg-card": "#fcfcfa",
        "fg-muted": "#939293",
        "fg-dim": "#727072",
        "fg-faint": "#3a3539",
        "fg-inverted": "#2d2a2e",
        "bg-inverted": "#fcfcfa",
        "toast-info": "#78dce8",
        "toast-warn": "#ffd866",
        "toast-error": "#ff6188",
    },
    markdown_styles={
        "markdown.paragraph": "#fcfcfa",
        "markdown.text": "#fcfcfa",
        "markdown.h1": "bold #ffd866",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #ff6188",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #a9dc76",
        "markdown.h4": "bold #78dce8",
        "markdown.h5": "bold #ab9df2",
        "markdown.h6": "bold #fc9867",
        "markdown.code": "#fcfcfa on #3a3539",
        "markdown.code_block": "#fcfcfa on #3a3539",
        "markdown.block_quote": "#fcfcfa on #221f22",
        "markdown.list": "#939293",
        "markdown.item": "#fcfcfa",
        "markdown.item.bullet": "bold #ffd866",
        "markdown.item.number": "bold #ffd866",
        "markdown.table.border": "#3a3539",
        "markdown.table.header": "bold #fcfcfa",
        "markdown.hr": "#3a3539",
        "markdown.link": "underline #78dce8",
        "markdown.link_url": "underline #78dce8",
        "markdown.em": "italic #fcfcfa",
        "markdown.strong": "bold #fcfcfa",
        "markdown.s": "strike #727072",
    },
    syntax_tokens={
        Token.Keyword: "#ff6188",
        Token.Keyword.Namespace: "#ff6188",
        Token.Keyword.Type: "#78dce8",
        Token.Keyword.Declaration: "#ff6188",
        Token.Name.Function: "#a9dc76",
        Token.Name.Class: "#78dce8",
        Token.Name.Tag: "#ff6188",
        Token.Name.Attribute: "#a9dc76",
        Token.Name.Property: "#fc9867",
        Token.Name.Variable: "#fcfcfa",
        Token.Name.Constant: "#ab9df2",
        Token.Name.Builtin: "#78dce8",
        Token.Name.Label: "#78dce8",
        Token.Name.Entity: "#78dce8",
        Token.Name.Decorator: "#a9dc76",
        Token.Name.Other: "#fcfcfa",
        Token.Name: "#fcfcfa",
        Token.String: "#ffd866",
        Token.String.Doc: "#ffd866",
        Token.Number: "#ab9df2",
        Token.Number.Hex: "#ab9df2",
        Token.Literal: "#ab9df2",
        Token.Operator: "#ff6188",
        Token.Punctuation: "#fcfcfa",
        Token.Comment: "#727072 italic",
    },
)

# --- Solarized Dark ---
SOLARIZED_DARK = Theme(
    name="solarized-dark",
    label="Solarized Dark",
    dark=True,
    primary="#839496",
    secondary="#93a1a1",
    muted="#586e75",
    subtle="#657b83",
    tcss_vars={
        "bg-app": "#002b36",
        "bg-surface": "#073642",
        "bg-elevated": "#003845",
        "bg-hover": "#586e75",
        "border-subtle": "#073642",
        "border-strong": "#586e75",
        "fg-primary": "#839496",
        "fg-body": "#839496",
        "fg-secondary": "#93a1a1",
        "fg-card": "#93a1a1",
        "fg-muted": "#657b83",
        "fg-dim": "#586e75",
        "fg-faint": "#073642",
        "fg-inverted": "#002b36",
        "bg-inverted": "#839496",
        "toast-info": "#268bd2",
        "toast-warn": "#b58900",
        "toast-error": "#dc322f",
    },
    markdown_styles={
        "markdown.paragraph": "#839496",
        "markdown.text": "#839496",
        "markdown.h1": "bold #b58900",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #268bd2",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #2aa198",
        "markdown.h4": "bold #859900",
        "markdown.h5": "bold #d33682",
        "markdown.h6": "bold #cb4b16",
        "markdown.code": "#839496 on #003845",
        "markdown.code_block": "#839496 on #003845",
        "markdown.block_quote": "#93a1a1 on #073642",
        "markdown.list": "#657b83",
        "markdown.item": "#839496",
        "markdown.item.bullet": "bold #b58900",
        "markdown.item.number": "bold #b58900",
        "markdown.table.border": "#073642",
        "markdown.table.header": "bold #839496",
        "markdown.hr": "#073642",
        "markdown.link": "underline #268bd2",
        "markdown.link_url": "underline #268bd2",
        "markdown.em": "italic #839496",
        "markdown.strong": "bold #839496",
        "markdown.s": "strike #586e75",
    },
    syntax_tokens={
        Token.Keyword: "#859900",
        Token.Keyword.Namespace: "#859900",
        Token.Keyword.Type: "#b58900",
        Token.Keyword.Declaration: "#859900",
        Token.Name.Function: "#268bd2",
        Token.Name.Class: "#b58900",
        Token.Name.Tag: "#dc322f",
        Token.Name.Attribute: "#2aa198",
        Token.Name.Property: "#268bd2",
        Token.Name.Variable: "#839496",
        Token.Name.Constant: "#d33682",
        Token.Name.Builtin: "#b58900",
        Token.Name.Label: "#268bd2",
        Token.Name.Entity: "#2aa198",
        Token.Name.Decorator: "#859900",
        Token.Name.Other: "#839496",
        Token.Name: "#839496",
        Token.String: "#2aa198",
        Token.String.Doc: "#2aa198",
        Token.Number: "#d33682",
        Token.Number.Hex: "#d33682",
        Token.Literal: "#d33682",
        Token.Operator: "#859900",
        Token.Punctuation: "#839496",
        Token.Comment: "#586e75 italic",
    },
)

# --- Zinc Light ---
ZINC_LIGHT = Theme(
    name="zinc-light",
    label="Zinc Light",
    dark=False,
    primary="#09090b",
    secondary="#18181b",
    muted="#71717a",
    subtle="#52525b",
    tcss_vars={
        "bg-app": "#ffffff",
        "bg-surface": "#f4f4f5",
        "bg-elevated": "#e4e4e7",
        "bg-hover": "#d4d4d8",
        "border-subtle": "#e4e4e7",
        "border-strong": "#d4d4d8",
        "fg-primary": "#09090b",
        "fg-body": "#18181b",
        "fg-secondary": "#27272a",
        "fg-card": "#27272a",
        "fg-muted": "#52525b",
        "fg-dim": "#71717a",
        "fg-faint": "#a1a1aa",
        "fg-inverted": "#ffffff",
        "bg-inverted": "#09090b",
        "toast-info": "#2563eb",
        "toast-warn": "#d97706",
        "toast-error": "#dc2626",
    },
    markdown_styles={
        "markdown.paragraph": "#18181b",
        "markdown.text": "#18181b",
        "markdown.h1": "bold #09090b",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #09090b",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #09090b",
        "markdown.h4": "bold #09090b",
        "markdown.h5": "bold #09090b",
        "markdown.h6": "bold #09090b",
        "markdown.code": "#09090b on #e4e4e7",
        "markdown.code_block": "#18181b on #e4e4e7",
        "markdown.block_quote": "#27272a on #f4f4f5",
        "markdown.list": "#52525b",
        "markdown.item": "#18181b",
        "markdown.item.bullet": "bold #52525b",
        "markdown.item.number": "bold #52525b",
        "markdown.table.border": "#e4e4e7",
        "markdown.table.header": "bold #09090b",
        "markdown.hr": "#e4e4e7",
        "markdown.link": "underline #2563eb",
        "markdown.link_url": "underline #2563eb",
        "markdown.em": "italic #18181b",
        "markdown.strong": "bold #09090b",
        "markdown.s": "strike #71717a",
    },
    syntax_tokens={
        Token.Keyword: "#a855f7",
        Token.Keyword.Namespace: "#a855f7",
        Token.Keyword.Type: "#d97706",
        Token.Keyword.Declaration: "#a855f7",
        Token.Name.Function: "#2563eb",
        Token.Name.Class: "#d97706",
        Token.Name.Tag: "#dc2626",
        Token.Name.Attribute: "#ea580c",
        Token.Name.Property: "#dc2626",
        Token.Name.Variable: "#09090b",
        Token.Name.Constant: "#ea580c",
        Token.Name.Builtin: "#d97706",
        Token.Name.Label: "#2563eb",
        Token.Name.Entity: "#0891b2",
        Token.Name.Decorator: "#2563eb",
        Token.Name.Other: "#dc2626",
        Token.Name: "#09090b",
        Token.String: "#16a34a",
        Token.String.Doc: "#16a34a",
        Token.Number: "#ea580c",
        Token.Number.Hex: "#ea580c",
        Token.Literal: "#ea580c",
        Token.Operator: "#0891b2",
        Token.Punctuation: "#52525b",
        Token.Comment: "#71717a italic",
    },
)



# --- GitHub Dark ---
GITHUB_DARK = Theme(
    name="github-dark",
    label="GitHub Dark",
    dark=True,
    primary="#c9d1d9",
    secondary="#e6edf3",
    muted="#8b949e",
    subtle="#58a6ff",
    tcss_vars={
        "bg-app": "#0d1117",
        "bg-surface": "#010409",
        "bg-elevated": "#161b22",
        "bg-hover": "#21262d",
        "border-subtle": "#21262d",
        "border-strong": "#30363d",
        "fg-primary": "#c9d1d9",
        "fg-body": "#c9d1d9",
        "fg-secondary": "#e6edf3",
        "fg-card": "#e6edf3",
        "fg-muted": "#8b949e",
        "fg-dim": "#6e7681",
        "fg-faint": "#21262d",
        "fg-inverted": "#0d1117",
        "bg-inverted": "#c9d1d9",
        "toast-info": "#58a6ff",
        "toast-warn": "#d29922",
        "toast-error": "#f85149",
    },
    markdown_styles={
        "markdown.paragraph": "#c9d1d9",
        "markdown.text": "#c9d1d9",
        "markdown.h1": "bold #58a6ff",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #58a6ff",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #79c0ff",
        "markdown.h4": "bold #58a6ff",
        "markdown.h5": "bold #d29922",
        "markdown.h6": "bold #f85149",
        "markdown.code": "#c9d1d9 on #161b22",
        "markdown.code_block": "#c9d1d9 on #161b22",
        "markdown.block_quote": "#e6edf3 on #010409",
        "markdown.list": "#8b949e",
        "markdown.item": "#c9d1d9",
        "markdown.item.bullet": "bold #58a6ff",
        "markdown.item.number": "bold #58a6ff",
        "markdown.table.border": "#21262d",
        "markdown.table.header": "bold #c9d1d9",
        "markdown.hr": "#21262d",
        "markdown.link": "underline #58a6ff",
        "markdown.link_url": "underline #58a6ff",
        "markdown.em": "italic #c9d1d9",
        "markdown.strong": "bold #c9d1d9",
        "markdown.s": "strike #6e7681",
    },
    syntax_tokens={
        Token.Keyword: "#ff7b72",
        Token.Keyword.Namespace: "#ff7b72",
        Token.Keyword.Type: "#ffa657",
        Token.Keyword.Declaration: "#ff7b72",
        Token.Name.Function: "#d2a8ff",
        Token.Name.Class: "#ffa657",
        Token.Name.Tag: "#7ee787",
        Token.Name.Attribute: "#79c0ff",
        Token.Name.Property: "#79c0ff",
        Token.Name.Variable: "#ffa657",
        Token.Name.Constant: "#79c0ff",
        Token.Name.Builtin: "#ffa657",
        Token.Name.Label: "#79c0ff",
        Token.Name.Entity: "#79c0ff",
        Token.Name.Decorator: "#d2a8ff",
        Token.Name.Other: "#c9d1d9",
        Token.Name: "#c9d1d9",
        Token.String: "#a5d6ff",
        Token.String.Doc: "#a5d6ff",
        Token.Number: "#79c0ff",
        Token.Number.Hex: "#79c0ff",
        Token.Literal: "#79c0ff",
        Token.Operator: "#ff7b72",
        Token.Punctuation: "#c9d1d9",
        Token.Comment: "#8b949e italic",
    },
)

# --- GitHub Light ---
GITHUB_LIGHT = Theme(
    name="github-light",
    label="GitHub Light",
    dark=False,
    primary="#1f2328",
    secondary="#24292f",
    muted="#656d76",
    subtle="#0969da",
    tcss_vars={
        "bg-app": "#ffffff",
        "bg-surface": "#f6f8fa",
        "bg-elevated": "#eaeef2",
        "bg-hover": "#d0d7de",
        "border-subtle": "#eaeef2",
        "border-strong": "#d0d7de",
        "fg-primary": "#1f2328",
        "fg-body": "#1f2328",
        "fg-secondary": "#24292f",
        "fg-card": "#24292f",
        "fg-muted": "#656d76",
        "fg-dim": "#8c959f",
        "fg-faint": "#afb8c1",
        "fg-inverted": "#ffffff",
        "bg-inverted": "#1f2328",
        "toast-info": "#0969da",
        "toast-warn": "#9a6700",
        "toast-error": "#cf222e",
    },
    markdown_styles={
        "markdown.paragraph": "#1f2328",
        "markdown.text": "#1f2328",
        "markdown.h1": "bold #0969da",
        "markdown.h1.border": "none",
        "markdown.h2": "bold #0969da",
        "markdown.h2.border": "none",
        "markdown.h3": "bold #0550ae",
        "markdown.h4": "bold #0969da",
        "markdown.h5": "bold #9a6700",
        "markdown.h6": "bold #cf222e",
        "markdown.code": "#1f2328 on #eaeef2",
        "markdown.code_block": "#1f2328 on #eaeef2",
        "markdown.block_quote": "#24292f on #f6f8fa",
        "markdown.list": "#656d76",
        "markdown.item": "#1f2328",
        "markdown.item.bullet": "bold #0969da",
        "markdown.item.number": "bold #0969da",
        "markdown.table.border": "#eaeef2",
        "markdown.table.header": "bold #1f2328",
        "markdown.hr": "#eaeef2",
        "markdown.link": "underline #0969da",
        "markdown.link_url": "underline #0969da",
        "markdown.em": "italic #1f2328",
        "markdown.strong": "bold #1f2328",
        "markdown.s": "strike #8c959f",
    },
    syntax_tokens={
        Token.Keyword: "#cf222e",
        Token.Keyword.Namespace: "#cf222e",
        Token.Keyword.Type: "#953800",
        Token.Keyword.Declaration: "#cf222e",
        Token.Name.Function: "#8250df",
        Token.Name.Class: "#953800",
        Token.Name.Tag: "#116329",
        Token.Name.Attribute: "#0550ae",
        Token.Name.Property: "#0550ae",
        Token.Name.Variable: "#953800",
        Token.Name.Constant: "#0550ae",
        Token.Name.Builtin: "#953800",
        Token.Name.Label: "#0550ae",
        Token.Name.Entity: "#0550ae",
        Token.Name.Decorator: "#8250df",
        Token.Name.Other: "#1f2328",
        Token.Name: "#1f2328",
        Token.String: "#0a3069",
        Token.String.Doc: "#0a3069",
        Token.Number: "#0550ae",
        Token.Number.Hex: "#0550ae",
        Token.Literal: "#0550ae",
        Token.Operator: "#cf222e",
        Token.Punctuation: "#1f2328",
        Token.Comment: "#6e7781 italic",
    },
)

BUILTIN_THEMES: list[Theme] = [
    ZINC_DARK,
    DRACULA,
    CATPPUCCIN_MOCHA,
    TOKYO_NIGHT,
    NORD,
    GRUVBOX,
    ONE_DARK,
    ROSE_PINE,
    MONOKAI_PRO,
    SOLARIZED_DARK,
    GITHUB_DARK,
    GITHUB_LIGHT,
    ZINC_LIGHT,
]
