from __future__ import annotations

import inspect
import os
from typing import Any, List

from johnston.core.interfaces.host import HostProtocol


def _is_mock(obj: Any) -> bool:
    return obj is not None and type(obj).__name__.startswith(("MagicMock", "Mock", "AsyncMock"))


def _has_host_method(host: Any, method_name: str) -> bool:
    if host is None:
        return False
    if _is_mock(host):
        return method_name in getattr(host, "__dict__", {})
    return callable(getattr(host, method_name, None))


class ToolContext:
    """Unified execution context for tools (isolates UI from business logic)"""

    def __init__(
        self,
        app: Any = None,
        is_subagent: bool = False,
        cwd: str | None = None,
        host: HostProtocol | None = None,
    ):
        target = host if host is not None else app
        role = getattr(target, "role", "")
        raw_target = target
        if target is not None and not type(target).__name__.startswith(("MagicMock", "Mock", "AsyncMock")):
            inner_app = getattr(target, "host", None) or getattr(target, "app", None)
            if inner_app is not None:
                if cwd is None:
                    cwd = getattr(target, "cwd", None) or getattr(target, "project_dir", None)
                is_subagent = getattr(target, "is_subagent", is_subagent)
                if not role:
                    role = getattr(target, "role", "")
                target = inner_app
        self.host = target
        session = None
        if raw_target is not None:
            if type(raw_target).__name__.startswith(("MagicMock", "Mock", "AsyncMock")):
                if "session" in getattr(raw_target, "__dict__", {}):
                    session = raw_target.session
            else:
                session = getattr(raw_target, "session", None)
        self.session = session

        def _get_bool(obj: Any, attr: str) -> bool:
            return getattr(obj, attr, False) is True

        self.is_subagent = bool(is_subagent) or _get_bool(raw_target, "is_subagent") or _get_bool(target, "is_subagent")
        self.is_headless = _get_bool(raw_target, "is_headless") or _get_bool(target, "is_headless")
        self.is_interactive = not (self.is_subagent or self.is_headless)
        self.subagent_role = role or ("worker" if self.is_subagent else "")
        self.cwd = None
        # Only trust a real string path (guard against MagicMock autogenerated attrs) and
        # make sure it exists before using it as a process/working directory.
        candidate = cwd
        if candidate is None and target is not None:
            candidate = getattr(target, "project_dir", None) or getattr(target, "cwd", None)
        if isinstance(candidate, str) and candidate.strip():
            abs_cwd = os.path.realpath(os.path.abspath(candidate))
            if os.path.isdir(abs_cwd):
                self.cwd = abs_cwd
        self._fallback_background_widgets: dict[str, Any] = {}
        self._fallback_foreground_tasks: dict[str, Any] = {}

    @property
    def app(self) -> Any:
        """Backward compatibility alias for host."""
        return self.host

    @app.setter
    def app(self, value: Any) -> None:
        self.host = value

    # ------------------------------------------------------------------ #
    # Host delegation helpers. Each call is guarded so a host that lacks a
    # capability degrades gracefully (returns None / no-op / empty).
    # ------------------------------------------------------------------ #

    def _host_call(self, name: str, *args, **kwargs) -> Any:
        """Safely invoke a host protocol method if present; guard awaitables."""
        host = self.host
        fn = getattr(host, name, None) if host is not None else None
        if not callable(fn):
            return None
        res = fn(*args, **kwargs)
        if inspect.iscoroutine(res):
            # Synchronous context cannot await; callers awaiting this get None
            # so they never hang waiting on an un-driven coroutine.
            return None
        return res

    async def ask_user(self, questions: list[dict]) -> str:
        """Ask the user questions via the host (async-capable)."""
        host = self.host
        fn = getattr(host, "ask_user", None) if host is not None else None
        if not callable(fn):
            return ""
        res = fn(questions)
        if inspect.isawaitable(res):
            res = await res
        return res if isinstance(res, str) else str(res or "")

    def trigger_ai_response(self, prompt: str) -> None:
        if self.host and callable(getattr(self.host, "trigger_ai_response", None)):
            self.host.trigger_ai_response(prompt, show_in_ui=False)

    def refresh_status(self) -> None:
        if self.host:
            self._host_call("refresh_status_footer")

    def mark_subagent_status(self, session_id: str, status: str, result: str = "") -> None:
        """Notify the host that a background subagent finished with ``status``.

        The host (UI zone) repaints the linked invoke_subagent tool card from
        running (yellow) to done/error/cancelled. No-op when unsupported.
        """
        self._host_call("on_subagent_tool_completed", session_id, status, result)

    @property
    def task_manager(self) -> Any | None:
        """Host task manager attribute (or protocol method fallback)."""
        if not self.host:
            return None
        return getattr(self.host, "task_manager", None)

    @property
    def provider_manager(self) -> Any | None:
        """Host provider manager (``pm``) attribute."""
        if not self.host:
            return None
        return getattr(self.host, "pm", None)

    @property
    def session_id(self) -> str | None:
        """Current session id attribute."""
        if getattr(self, "session", None):
            sid = getattr(self.session, "id", None)
            if isinstance(sid, str):
                return sid
        if not self.host:
            return None
        sid = getattr(self.host, "current_session_id", None)
        return sid if isinstance(sid, str) else None

    @property
    def sandbox_enabled(self) -> bool:
        """Returns whether shell command sandboxing is active."""
        if hasattr(self, "_sandbox_enabled") and self._sandbox_enabled is not None:
            return bool(self._sandbox_enabled)
        if self.is_read_only:
            return True
        if self.host is None:
            return False
        val = getattr(self.host, "sandbox_enabled", False)
        if isinstance(val, bool):
            return val
        if isinstance(val, (int, str)):
            return str(val).lower() in ("true", "1", "yes", "on")
        return False

    @sandbox_enabled.setter
    def sandbox_enabled(self, value: bool) -> None:
        self._sandbox_enabled = bool(value)

    @property
    def is_read_only(self) -> bool:
        """Returns whether the current role or execution context is read-only."""
        if hasattr(self, "_is_read_only") and self._is_read_only is not None:
            return bool(self._is_read_only)
        if getattr(self.host, "is_read_only", False) is True:
            return True
        try:
            from johnston.core.application.roles.role_registry import RoleRegistry

            role_name = self.subagent_role or getattr(self.host, "role", "")
            if isinstance(role_name, str) and role_name:
                role_def = RoleRegistry.get_instance().get_role(role_name, project_dir=self.project_dir)
                if getattr(role_def, "read_only", False) is True:
                    return True
        except Exception:
            pass
        return False

    @is_read_only.setter
    def is_read_only(self, value: bool) -> None:
        self._is_read_only = bool(value)

    @property
    def project_dir(self) -> str:
        """Returns the project directory from host app, or fallback to self.cwd / os.getcwd()."""
        if self.host:
            pdir = getattr(self.host, "project_dir", None)
            if isinstance(pdir, str) and pdir.strip():
                return pdir
        return self.cwd or os.getcwd()

    @property
    def background_tasks(self) -> List[Any]:
        """Live tasks currently managed by the app's TaskManager."""
        mgr = self.task_manager
        if mgr is not None:
            return list(mgr)
        return []

    def add_background_task(self, task: Any) -> None:
        mgr = self.task_manager
        if mgr is not None:
            if getattr(task, "session_id", None) is None and hasattr(task, "__dict__"):
                try:
                    setattr(task, "session_id", self.session_id)
                except AttributeError:
                    pass
            mgr.register(task)
        self.refresh_status()

    def create_agent(self) -> Any:
        pm = self.provider_manager
        if pm is not None and hasattr(pm, "create_active_agent"):
            return pm.create_active_agent()
        return None

    @property
    def target_tool_widget(self) -> Any | None:
        """Return the current tool widget from the host if not a subagent."""
        if self.is_subagent or not self.host:
            return None
        return getattr(self.host, "current_tool_widget", None)

    def on_plan_update(self, plan: list, status: str = "") -> None:
        """Notify host of an updated execution plan."""
        if self.host:
            self._host_call("on_plan_update", plan, status)

    def attach_shell_widget(
        self,
        task_id: str,
        widget: Any,
        log_path: str | None = None,
        is_background: bool = False,
    ) -> None:
        """Link the shell tool card to the task for the completion repaint."""
        if not self.host or widget is None:
            return
        if _has_host_method(self.host, "attach_shell_widget"):
            self.host.attach_shell_widget(
                task_id, widget, log_path=log_path, is_background=is_background
            )
            return

        if is_background:
            if hasattr(widget, "mark_background"):
                try:
                    widget.mark_background(task_id, log_path)
                except Exception:
                    pass
            else:
                try:
                    setattr(widget, "background_task_id", task_id)
                    setattr(widget, "task_id", task_id)
                    if log_path:
                        setattr(widget, "log_path", log_path)
                except Exception:
                    pass
        self._fallback_background_widgets[task_id] = widget

    def detach_shell_widget(self, task_id: str) -> None:
        """Unregister widget handle for shell task upon completion or drop."""
        if not self.host:
            return
        if _has_host_method(self.host, "detach_shell_widget"):
            self.host.detach_shell_widget(task_id)
            return
        self._fallback_background_widgets.pop(task_id, None)

    def register_foreground_shell_task(self, task_id: str, task: Any) -> None:
        """Register active foreground shell task so UI/actions mixin can cancel or background it."""
        if not self.host:
            return
        if _has_host_method(self.host, "register_foreground_shell_task"):
            self.host.register_foreground_shell_task(task_id, task)
            return
        fg = getattr(self.host, "_foreground_shell_tasks", None)
        if isinstance(fg, dict):
            fg[task_id] = task
        elif _is_mock(self.host) or hasattr(self.host, "__dict__"):
            try:
                if not isinstance(fg, dict):
                    fg = {}
                    setattr(self.host, "_foreground_shell_tasks", fg)
                fg[task_id] = task
            except Exception:
                self._fallback_foreground_tasks[task_id] = task
        else:
            self._fallback_foreground_tasks[task_id] = task

    def cleanup_foreground_shell_task(self, task_id: str) -> None:
        """Unregister foreground shell task upon exit or conversion."""
        if not self.host:
            return
        if _has_host_method(self.host, "cleanup_foreground_shell_task"):
            self.host.cleanup_foreground_shell_task(task_id)
            return
        fg = getattr(self.host, "_foreground_shell_tasks", None)
        if isinstance(fg, dict):
            fg.pop(task_id, None)
        self._fallback_foreground_tasks.pop(task_id, None)

    def find_task(self, task_id: str) -> Any | None:
        """Find task in background tasks registry or active foreground tasks."""
        if not task_id:
            return None
        from johnston.core.infrastructure.tasks.manage import filter_to_session

        # 1. Scoped to current session
        tasks = filter_to_session(self.background_tasks or [], self.session_id or "")
        for t in tasks:
            if getattr(t, "task_id", None) == task_id or getattr(t, "id", None) == task_id:
                return t

        # 2. Fallback to global tasks (across sessions)
        for t in self.background_tasks or []:
            if getattr(t, "task_id", None) == task_id or getattr(t, "id", None) == task_id:
                return t

        # 3. Check active foreground tasks via host method or fallback
        if self.host:
            if _has_host_method(self.host, "get_foreground_shell_task"):
                t = self.host.get_foreground_shell_task(task_id)
                if t is not None:
                    return t
            fg = getattr(self.host, "_foreground_shell_tasks", None)
            if isinstance(fg, dict) and task_id in fg:
                return fg[task_id]
        if task_id in self._fallback_foreground_tasks:
            return self._fallback_foreground_tasks[task_id]
        return None

    def terminate_task_widget(
        self,
        task_id: str,
        output: str = "[killed]",
        status: str = "done",
    ) -> None:
        """Safely terminate and detach linked UI widget for a killed task."""
        if not self.host:
            return
        if _has_host_method(self.host, "terminate_task_widget"):
            self.host.terminate_task_widget(task_id, output=output, status=status)
            return
        widget = self._fallback_background_widgets.pop(task_id, None)
        if widget is not None and hasattr(widget, "set_result"):
            try:
                widget.set_result(output, status=status)
            except Exception:
                pass


