"""Tool name and argument alias tables.

Centralizes the alias maps so the registry stays focused on dispatch. The registry
imports these tables and provides the `normalize_tool_name`/`normalize_tool_args`
helpers that resolve against them.
"""

from typing import Dict

ALIAS_MAP: Dict[str, str] = {
    "write": "create",
    "write_file": "create",
    "create_file": "create",
    "save_file": "create",
    "write_to_file": "create",
    "touch": "create",
    "read_file": "read",
    "view_file": "read",
    "cat": "read",
    "read_file_content": "read",
    "edit_file": "edit",
    "replace_file_content": "edit",
    "multi_replace_file_content": "edit",
    "update_file": "edit",
    "modify_file": "edit",
    "str_replace_editor": "edit",
    "replace": "edit",
    "multi_replace": "edit",
    "patch": "edit",
    "apply_patch": "edit",
    "subagent": "invoke_subagent",
    "spawn_subagent": "invoke_subagent",
    "run_subagent": "invoke_subagent",
    "delegate": "invoke_subagent",
    "spawn": "invoke_subagent",
    "run_agent": "invoke_subagent",
    "terminal": "shell",
    "exec": "shell",
    "run_command": "shell",
    "bash": "shell",
    "cmd": "shell",
    "run": "shell",
    "ask": "ask_user",
    "ask_question": "ask_user",
    "plan": "update_plan",
    "set_plan": "update_plan",
    "fetch": "web_fetch",
    "fetch_url": "web_fetch",
    "browse": "web_fetch",
    "get": "web_fetch",
    "curl": "web_fetch",
    "subagents": "manage_subagent",
    "kill_subagent": "manage_subagent",
    "shells": "manage_shell",
    "processes": "manage_shell",
    "manage_processes": "manage_shell",
    "bg_processes": "manage_shell",
}


# Canonical names for the fields inside an `edit`/`multi_edit` replacement chunk.
# Single source of truth shared by the registry's chunk normalizer and the
# `edit` param-alias table (which also carries path/description aliases).
EDIT_CHUNK_ALIAS_MAP: Dict[str, str] = {
    "target_content": "old_str",
    "TargetContent": "old_str",
    "old_content": "old_str",
    "search": "old_str",
    "oldStr": "old_str",
    "old": "old_str",
    "replacement_content": "new_str",
    "ReplacementContent": "new_str",
    "new_content": "new_str",
    "replace": "new_str",
    "newStr": "new_str",
    "new": "new_str",
    "start_line": "start_line",
    "StartLine": "start_line",
    "start": "start_line",
    "end_line": "end_line",
    "EndLine": "end_line",
    "end": "end_line",
    "allow_multiple": "allow_multiple",
    "multiple": "allow_multiple",
}

PARAM_ALIAS_MAP: Dict[str, Dict[str, str]] = {
    "shell": {
        "cmd": "command",
        "script": "command",
        "command_line": "command",
        "exec": "command",
        "time_limit": "timeout",
        "max_seconds": "timeout",
        "timeout_seconds": "timeout",
        "background": "run_in_background",
        "async": "run_in_background",
        "is_async": "run_in_background",
        "bg": "run_in_background",
        "skip_confirmation": "skip_confirm",
    },
    "read": {
        "file_path": "path",
        "filepath": "path",
        "file": "path",
        "filename": "path",
        "target_file": "path",
        "uri": "path",
        "url": "path",
        "start": "start_line",
        "startLine": "start_line",
        "from_line": "start_line",
        "line_start": "start_line",
        "end": "end_line",
        "endLine": "end_line",
        "to_line": "end_line",
        "line_end": "end_line",
        "last_line": "end_line",
        "offset": "start_line",
        "line_offset": "start_line",
        "start_offset": "start_line",
        "content_offset": "content_offset",
        "contentOffset": "content_offset",
        "byte_offset": "content_offset",
        "detail_level": "detail",
        "image_detail": "detail",
    },
    "create": {
        "path": "target_file",
        "file_path": "target_file",
        "filepath": "target_file",
        "file": "target_file",
        "filename": "target_file",
        "destination": "target_file",
        "content": "code",
        "text": "code",
        "contents": "code",
        "file_content": "code",
        "file_contents": "code",
        "body": "code",
        "data": "code",
        "summary": "description",
        "desc": "description",
        "reason": "description",
    },
    "edit": {
        "path": "target_file",
        "target_file": "target_file",
        "TargetFile": "target_file",
        "file_path": "target_file",
        "filepath": "target_file",
        "file": "target_file",
        "filename": "target_file",
        "old_str": "old_str",
        "old_string": "old_str",
        "new_str": "new_str",
        "new_string": "new_str",
        "desc": "description",
        "prompt": "instruction",
        "replacement_chunks": "edits",
        "ReplacementChunks": "edits",
        "chunks": "edits",
        "changes": "edits",
        "replacements": "edits",
        **EDIT_CHUNK_ALIAS_MAP,
    },
    "multi_edit": {
        "path": "target_file",
        "target_file": "target_file",
        "TargetFile": "target_file",
        "file_path": "target_file",
        "filepath": "target_file",
        "file": "target_file",
        "replacement_chunks": "edits",
        "ReplacementChunks": "edits",
        "chunks": "edits",
        "changes": "edits",
        "replacements": "edits",
        "start_line": "start_line",
        "end_line": "end_line",
        "allow_multiple": "allow_multiple",
    },
    "web_fetch": {
        "uri": "url",
        "link": "url",
        "path": "url",
        "address": "url",
        "page_url": "url",
        "as_raw": "raw",
    },
    "ask_user": {
        "question_list": "questions",
        "all_questions": "questions",
        "qs": "questions",
    },
    "update_plan": {
        "steps": "plan",
        "tasks": "plan",
        "items": "plan",
        "todo": "plan",
        "note": "explanation",
    },
    "invoke_subagent": {
        "type": "subagent_type",
        "subagent": "subagent_type",
        "name": "subagent_type",
        "agent_type": "subagent_type",
        "agent": "subagent_type",
        "role": "subagent_type",
        "instructions": "prompt",
        "task": "prompt",
        "goal": "prompt",
        "message": "prompt",
        "mode": "workspace",
        "task_id": "session_id",
        "taskId": "session_id",
        "subagent_id": "session_id",
        "id": "session_id",
    },
    "manage_subagent": {
        "cmd": "action",
        "command": "action",
        "task_id": "session_id",
        "taskId": "session_id",
        "subagent_id": "session_id",
        "id": "session_id",
        "ids": "session_id",
        "subagent_ids": "session_id",
        "msg": "message",
        "async": "background",
        "run_async": "background",
        "show_all": "all",
    },
    "manage_shell": {
        "cmd": "action",
        "command": "action",
        "id": "task_id",
        "taskId": "task_id",
        "text": "input",
        "stdin": "input",
        "data": "input",
        "message": "input",
    },
}
