import os
from typing import Any, List


class ToolContext:
    """Unified execution context for tools (isolates UI from business logic)"""

    def __init__(self, app: Any = None, is_subagent: bool = False, cwd: str = None):
        from core.base_provider import BaseAgent

        if isinstance(app, BaseAgent) and getattr(getattr(app, "app", None), "push_screen", None) is not None:
            # If passed an agent (wraps a host Textual app), unwrap to the host app
            # so UI operations target the real app, pulling cwd/subagent flag off the agent.
            if cwd is None:
                cwd = getattr(app, "cwd", None) or getattr(app, "project_dir", None)
            is_subagent = getattr(app, "is_subagent", is_subagent)
            app = app.app
        self.app = app
        self.is_subagent = is_subagent or (getattr(app, "is_subagent", False) if app else False)
        self.cwd = None
        # Only trust a real string path (guard against MagicMock autogenerated attrs) and
        # make sure it exists before using it as a process/working directory.
        candidate = cwd
        if candidate is None and app is not None:
            candidate = getattr(app, "project_dir", None) or getattr(app, "cwd", None)
        if isinstance(candidate, str) and candidate.strip():
            abs_cwd = os.path.realpath(os.path.abspath(candidate))
            if os.path.isdir(abs_cwd):
                self.cwd = abs_cwd

    def refresh_status(self) -> None:
        if self.app and hasattr(self.app, "refresh_status_footer"):
            self.app.refresh_status_footer()

    @property
    def project_dir(self) -> str:
        """Returns the project directory from host app, or fallback to self.cwd / os.getcwd()."""
        if self.app:
            pdir = getattr(self.app, "project_dir", None)
            if isinstance(pdir, str) and pdir.strip():
                return pdir
        return self.cwd or os.getcwd()

    @property
    def background_tasks(self) -> List[Any]:
        """Live shell tasks currently managed by the app's TaskManager."""
        mgr = getattr(self.app, "task_manager", None) if self.app else None
        if mgr is not None:
            return [t for t in mgr if getattr(t, "kind", "") == "shell"]
        return []

    def add_background_task(self, task: Any) -> None:
        mgr = getattr(self.app, "task_manager", None) if self.app else None
        if mgr is not None:
            if getattr(task, "session_id", None) is None and hasattr(task, "__dict__"):
                try:
                    setattr(task, "session_id", getattr(self.app, "current_session_id", None))
                except AttributeError:
                    pass
            mgr.register(task)
        self.refresh_status()

    def create_agent(self) -> Any:
        if self.app and hasattr(self.app, "pm"):
            return self.app.pm.create_active_agent()
        return None

    def trigger_ai_response(self, prompt: str) -> None:
        if self.app:
            if hasattr(self.app, "trigger_ai_response"):
                self.app.trigger_ai_response(prompt, show_in_ui=False)
            elif hasattr(self.app, "generate_ai_response"):
                if getattr(self.app, "is_generating", False) and hasattr(self.app, "message_queue"):
                    self.app.message_queue.append((prompt, False))
                else:
                    self.app.generate_ai_response(prompt, show_in_ui=False)
