import inspect
import os
from typing import Any, List


class ToolContext:
    """Unified execution context for tools (isolates UI from business logic)"""

    def __init__(self, app: Any = None, is_subagent: bool = False, cwd: str = None):
        if app is not None and not type(app).__name__.startswith(("MagicMock", "Mock", "AsyncMock")):
            inner_app = getattr(app, "app", None)
            if inner_app is not None:
                if cwd is None:
                    cwd = getattr(app, "cwd", None) or getattr(app, "project_dir", None)
                is_subagent = getattr(app, "is_subagent", is_subagent)
                app = inner_app
        self.host = app
        self.is_subagent = is_subagent or (getattr(app, "is_subagent", False) if app else False)
        self.cwd = None
        # Only trust a real string path (guard against MagicMock autogenerated attrs) and
        # make sure it exists before using it as a process/working directory.
        candidate = cwd
        if candidate is None and app is not None:
            candidate = getattr(app, "project_dir", None) or getattr(app, "cwd", None)
        if isinstance(candidate, str) and candidate.strip():
            abs_cwd = os.path.realpath(os.path.abspath(candidate))
            if os.path.isdir(abs_cwd):
                self.cwd = abs_cwd

    # ------------------------------------------------------------------ #
    # Host delegation helpers. Each call is guarded so a host that lacks a
    # capability degrades gracefully (returns None / no-op / empty).
    # ------------------------------------------------------------------ #

    def _host_call(self, name: str, *args, **kwargs) -> Any:
        """Safely invoke a host protocol method if present; guard awaitables."""
        host = self.host
        fn = getattr(host, name, None) if host is not None else None
        if not callable(fn):
            return None
        res = fn(*args, **kwargs)
        if inspect.iscoroutine(res):
            # Synchronous context cannot await; callers awaiting this get None
            # so they never hang waiting on an un-driven coroutine.
            return None
        return res

    async def ask_user(self, questions: list[dict]) -> str:
        """Ask the user questions via the host (async-capable)."""
        host = self.host
        fn = getattr(host, "ask_user", None) if host is not None else None
        if not callable(fn):
            return ""
        res = fn(questions)
        if inspect.isawaitable(res):
            res = await res
        return res if isinstance(res, str) else str(res or "")

    def trigger_ai_response(self, prompt: str) -> None:
        if self.host and callable(getattr(self.host, "trigger_ai_response", None)):
            self.host.trigger_ai_response(prompt, show_in_ui=False)

    def refresh_status(self) -> None:
        if self.host:
            self._host_call("refresh_status_footer")

    def mark_subagent_status(self, session_id: str, status: str, result: str = "") -> None:
        """Notify the host that a background subagent finished with ``status``.

        The host (UI zone) repaints the linked invoke_subagent tool card from
        running (yellow) to done/error/cancelled. No-op when unsupported.
        """
        self._host_call("on_subagent_tool_completed", session_id, status, result)

    @property
    def task_manager(self) -> Any | None:
        """Host task manager attribute (or protocol method fallback)."""
        if not self.host:
            return None
        return getattr(self.host, "task_manager", None)

    @property
    def provider_manager(self) -> Any | None:
        """Host provider manager (``pm``) attribute."""
        if not self.host:
            return None
        return getattr(self.host, "pm", None)

    @property
    def session_id(self) -> str | None:
        """Current session id attribute."""
        if not self.host:
            return None
        return getattr(self.host, "current_session_id", None)

    @property
    def project_dir(self) -> str:
        """Returns the project directory from host app, or fallback to self.cwd / os.getcwd()."""
        if self.host:
            pdir = getattr(self.host, "project_dir", None)
            if isinstance(pdir, str) and pdir.strip():
                return pdir
        return self.cwd or os.getcwd()

    @property
    def background_tasks(self) -> List[Any]:
        """Live shell tasks currently managed by the app's TaskManager."""
        mgr = self.task_manager
        if mgr is not None:
            return [t for t in mgr if getattr(t, "kind", "") == "shell"]
        return []

    def add_background_task(self, task: Any) -> None:
        mgr = self.task_manager
        if mgr is not None:
            if getattr(task, "session_id", None) is None and hasattr(task, "__dict__"):
                try:
                    setattr(task, "session_id", self.session_id)
                except AttributeError:
                    pass
            mgr.register(task)
        self.refresh_status()

    def create_agent(self) -> Any:
        pm = self.provider_manager
        if pm is not None and hasattr(pm, "create_active_agent"):
            return pm.create_active_agent()
        return None
