from typing import Any, Dict

from tools.base import BaseTool, format_tool_error, tail_output


class ManageShellTool(BaseTool):
    name = "manage_shell"
    description = "Manage background shell processes: list, status, kill, send_input."
    schema = {
        "type": "function",
        "function": {
            "name": "manage_shell",
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["list", "status", "kill", "send_input"]},
                    "task_id": {"type": "string", "description": "Background task ID"},
                    "input": {"type": "string", "description": "Input text for send_input"},
                },
                "required": ["action"],
            },
        },
    }

    async def execute(self, args: Dict[str, Any], ctx: Any = None) -> str:
        from tools.registry import normalize_tool_args

        args = normalize_tool_args("manage_shell", args)
        ctx = self._ensure_context(ctx)
        action = args.get("action", "list").lower()
        task_id = (args.get("task_id") or "").strip()

        tasks = ctx.background_tasks
        if not tasks and not ctx.app:
            return format_tool_error("manager", name="none", detail="available")

        # Scope to the current session, matching the tasks screen and status footer.
        # Guard against MagicMock-style autogenerated attrs (see ToolContext.cwd).
        curr_sid = getattr(ctx.app, "current_session_id", None) if ctx.app else None
        if isinstance(curr_sid, str) and curr_sid:
            tasks = [t for t in tasks if getattr(t, "session_id", None) == curr_sid]

        def _task_not_found_msg(tid: str) -> str:
            active_ids = [t.task_id for t in tasks if getattr(t, "is_running", True)]
            if active_ids:
                ids_str = ", ".join(f"'{i}'" for i in active_ids)
                return format_tool_error("notfound", detail=f"[Hint: Active IDs: {ids_str}]", name=tid)
            return format_tool_error("notfound", detail="[Hint: No active background tasks]", name=tid)

        if action == "list":
            if not tasks:
                return "no tasks active"
            lines = ["Active Background Tasks:"]
            for t in tasks:
                status = "RUNNING" if t.is_running else "FINISHED"
                lines.append(f"- ID: {t.task_id} | Status: {status} | Command: {t.command}")
            return "\n".join(lines)

        elif action == "status":
            if not task_id:
                return format_tool_error("params", name="task_id", detail="required for 'status'")
            matching = [t for t in tasks if t.task_id == task_id]
            if not matching:
                return _task_not_found_msg(task_id)
            t = matching[0]
            out = t.get_formatted_output() if hasattr(t, "get_formatted_output") else "".join(t.output)
            out = tail_output(out, 4000)
            if t.is_running:
                return (
                    f"Task ID: {t.task_id}\nStatus: RUNNING\nCommand: {t.command}\n\nRecent Output:\n{out or '(No output yet)'}\n\n"
                    "Note: If Recent Output shows an interactive prompt (e.g., asking for input, confirmation [y/N], or 'Press RETURN'), "
                    f"you may call manage_shell(action='send_input', task_id='{t.task_id}', input='...') to answer it, or manage_shell(action='kill', task_id='{t.task_id}') to abort. "
                    "Otherwise, STOP calling manage_shell(status) in a loop and end your turn now."
                )
            return f"{t.task_id} FINISHED\nCommand: {t.command}\n\nRecent Output:\n{out or '(No output yet)'}"

        elif action in ("send_input", "input"):
            if not task_id:
                return format_tool_error("params", name="task_id", detail="required for 'send_input'")
            input_text = args.get("input", "")
            if input_text is None:
                input_text = ""
            matching = [t for t in tasks if t.task_id == task_id]
            if not matching:
                return _task_not_found_msg(task_id)
            t = matching[0]
            if not getattr(t, "is_running", False):
                return format_tool_error("notrunning", name=task_id)

            if hasattr(t, "send_input"):
                return await t.send_input(input_text)
            return format_tool_error("nowrite", name=task_id, detail="stdin not writable")

        elif action == "kill":
            if not task_id:
                return format_tool_error("params", name="task_id", detail="required for 'kill'")
            matching = [t for t in tasks if t.task_id == task_id]
            if not matching:
                return _task_not_found_msg(task_id)
            t = matching[0]
            if getattr(t, "is_running", False):
                try:
                    if hasattr(t, "kill"):
                        await t.kill()
                    elif getattr(t, "process", None) and t.process.returncode is None:
                        t.process.kill()
                    t.is_running = False
                    ctx.refresh_status()
                    return f"{task_id} killed"
                except Exception as e:
                    return format_tool_error("kill", detail=str(e), name=task_id)
            return format_tool_error("notrunning", name=task_id)

        return format_tool_error("action", detail="use 'list', 'status', 'kill', or 'send_input'", name=action)
