name: Publish to PyPI & GitHub Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish Python distribution to PyPI & GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create GitHub Release
      id-token: write  # Mandatory for PyPI Trusted Publishing (OIDC)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Lint and Run Tests
        run: |
          uv run ruff check .
          uv run python -m unittest discover -s tests

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
